### ISSUE TITLE
Setting the Payload Output to String

### ISSUE THREAD

**Issue by PLukomski** [boschrexroth/node-red-contrib-ctrlx-automation#6]
The help info for the CtrlX Datalayer Request node states you have the ability to set the output to a string, buffer, or JSON string.  Below is the info from the help:  

"The body of the response. The node can be configured to return the data as a string, attempt to parse it as a JSON string or leave it as a binary buffer."

However, I do not see a way in the node to be able to set the output type.  How do you accomplish this?

**Comment by krauskopf** [comment]
Sorry for the confusion. Configuration of the output format is a planned feature, but not yet part of this releases. Looks like the documentation was faster than the implementation.

For the moment, the data is always returned as a json object. For simple data types this consists of type and value. For complex types, the data object is returned directly as json.

For the planned feature we will make it configurable to return JSON (with type info),  value only (as string), binary format (with type info, probably encoded as flatbuffer).

I will leave this issue open until the feature is available.
