### ISSUE TITLE
DL Subcription - adding input as msg.path and options to control the node actions as msg.action

### ISSUE THREAD

**Issue by kookoolinoo** [boschrexroth/node-red-contrib-ctrlx-automation#61]
Hi,

Thx a lot for cool node-red-contrib-ctrlx-automation nodes.

I have 2 topics that maybe you would like to address with the next releases (I use currently version: 1.8.19):

1) Do you think that this would be a potential benefit if for the DL subscribe node we would have the property "path" as optional input e.g. msg.path (used to set the path to the Data Layer node which shall be subscribed to.) In a form of an array probably? Same as for "mqtt" node where it is called dynamic subscription and node gets input anchor.

Currently when using the DL subscription node I have to (but I would prefer not) hard code the DL path in the flow configuration via node-red GUI. I would prefer to send it with some payload and be able to catch potential problems afterwards.

BTW: I understand that one DL subscribe node makes one SSE call to the ctrlX DL node with a specific keepalive and subscriptions’ times. But at least sending more paths (e.g. as array of DL paths) in msg.path to this subscription node would be cool. E.g. subscription for same parameter but from different servo drives (the SSE REST allows such list of nodes).

2) It happens that when the machine which includes the drives is down/restarted - the corresponding DL paths are not existing anymore (or the DL paths were deleted automatically or due app failure) and ctrlX is still online we got error on the DL subscription node. It is OK I can catch it and at least I am aware. Do you think that adding also e.g. msg.action with names of the action the node should perform e.g.: "connect", "disconnect", "subscribe" and "unsubscribe".

In general: I want to subscribe to DL but only after some preparation of environment (=the ctrlX DL) for this operation - e.g. servodrives are up, everything is checked and ready to start the DL subscription and react on potential errors. 

Best regards,

Kookoolinoo

**Comment by krauskopf** [comment]
Hi @kookoolinoo,

I think both proposals are very valuable feature extensions. 👍 
Can't give you a date at the moment, but stay tuned for the next release. ;-)

BTW: Multiple "Data Layer Subscribe" nodes and their paths will be grouped together to a single SSE subscription. You can control this via the Data Layer Subscription Config Node". See also 
https://github.com/boschrexroth/node-red-contrib-ctrlx-automation/blob/master/doc/DEVELOPMENT.md for the detailed architecture.

Best Regards
Sebastian

**Comment by krauskopf** [comment]
Finally added with #71
