### ISSUE TITLE
pictures in Readme.md not vissible

### ISSUE THREAD

**Issue by YourCodeShepherd** [boschrexroth/node-red-contrib-ctrlx-automation#65]
The example pictures in the Readme.md are not visible since the last commit, as the paths of the source pictures has changed:
usage_overview_request.png --> examples_read_CPU_utilisation.png
usage_overview_subscribe.png --> examples_subscribe_CPU_utilisation.png

**Comment by krauskopf** [comment]
Fixed with #67
