### ISSUE TITLE
mass subscribe results in "DL_INVALID_ADDRESS"

### ISSUE THREAD

**Issue by YourCodeShepherd** [boschrexroth/node-red-contrib-ctrlx-automation#66]
I tested a mass subscribe via subscribe node but always get "DL_INVALID_ADDRESS". E.g. Path = ["framework/metrics/system/cpu-utilisation-percent","framework/metrics/system/memavailable-mb"]

when using the resulting string directly it is working:
https://127.0.0.1:8443/automation/api/v2/events?nodes=framework%2Fmetrics%2Fsystem%2Fcpu-utilisation-percent%2Cframework%2Fmetrics%2Fsystem%2Fmemavailable-mb&publishIntervalMs=100

I checked the code but not figure out why it is not working. Path is created in [CtrlxDatalayerSubscription.js line 118](https://github.com/boschrexroth/node-red-contrib-ctrlx-automation/blob/7469c0dc491de821b336818a9cd7129bff2ed392/lib/CtrlxDatalayerSubscription.js#L118)

**Comment by krauskopf** [comment]
Finally added with #71
